# Site settings
title: Writings by Pablo G. M. 
description: A collection of essays, articles and books where Pablo Gonzalez Moctezuma for which contributed
keywords: restoration, landscape, milpa, smallholders
author: Pablo G. M. in a template by Wferr
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
